### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by qmfrederik** [gnustep/tools-windows-msvc#32]
The previous release in this repo dates back to 2023-01-04. A couple of notable changes have gone in since (including support for libs-gui).  Any chance you could tag a new release?  That would give us stable release artifacts to use in projects which depend on this project.

**Comment by triplef** [comment]
Yes I’ve been meaning to do that as well. There is one more issue I’d like to fix before, which is that I found that libs-base in release builds is currently built without optimization due to the way `CFLAGS` are used by autoconf / GNUstep-Make. I’m planning to look into this and will tag a release once that’s done.

**Comment by triplef** [comment]
A new release is now available:
https://github.com/gnustep/tools-windows-msvc/releases/tag/release-20231228
